<a href="https://colab.research.google.com/github/DiptangshuPattadar/python_new/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [5]:
my_list=[1,2,3,4,5]
arr=np.array(my_list)

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([2])
arr_result=arr+arr2
print(arr_result)

[3 4 5 6 7]


In [9]:
arr_result

array([3, 4, 5, 6, 7])

In [10]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([3])
arr_result=arr1*arr2
print(arr_result)


[ 3  6  9 12 15]


In [11]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([2])
arr_result=arr1/arr2
print(arr_result)


[0.5 1.  1.5 2.  2.5]


Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])


In [12]:
arr=np.array([1,2,3,4,5])
reversed_arr=np.flip([arr])
print(reversed_arr)

[[5 4 3 2 1]]


In [13]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
unique_values, counts = np.unique(x, return_counts=True)
most_frequent_value = unique_values[np.argmax(counts)]

indices = np.where(x == most_frequent_value)[0]
print(unique_values)
print(indices)

[1 2 3 4 5]
[0 5 7 8 9]


In [14]:
 y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
 unique_values, counts = np.unique(y, return_counts=True)
 most_frequent_value = unique_values[np.argmax(counts)]

 indices = np.where(x == most_frequent_value)[0]
 print(unique_values)
 print(indices)

[1 2 3 4]
[0 5 7 8 9]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column


In [15]:
arr=np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

elem1 =arr[0,1]
elem2 = arr[2,0]
print(elem1)
print(elem2)


20
70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [40]:
Dipz=np.linspace(10,100,25)
print(Dipz)
print(Dipz.ndim)
print(Dipz.shape)
print(Dipz.size)
print(Dipz.dtype)
print(Dipz.nbytes)
Dipz_transposed = Dipz.reshape(25, 1)
print("\nTransposed array using reshape():\n", Dipz_transposed)
print("\nTransposed array using T attribute:\n", Dipz.T)


[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
1
(25,)
25
float64
200

Transposed array using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transposed array using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [39]:
ucs420 = np.array([[10, 20, 30,
                  40, 50, 60,
                  70, 80, 90,
                  15, 20, 35]])
print(np.median(ucs420))
print(np.max(ucs420))
print(np.min(ucs420))
print(np.unique(ucs420))
ucs420_reshaped = ucs420.reshape(4, 3)
print(ucs420_reshaped)
ucs420_resized = np.resize(ucs420, (2, 3))
print(ucs420_resized)

37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
